### ISSUE TITLE
`--version` returns incorrect version

### ISSUE THREAD

**Issue by caius** [alexwlchan/safari-webarchiver#11]
I've built it from the 1.0.0 tags using https://github.com/alexwlchan/safari-webarchiver/archive/refs/tags/v1.0.0.tar.gz and then compiling with `swiftc save_safari_webarchive.swift`. Interrogating the version number returns an older version though:

```
$ save_safari_webarchive --version
save_safari_webarchive 0.9
```

Guessing this has just been missed during the release process, looks like https://github.com/alexwlchan/safari-webarchiver/blob/main/save_safari_webarchive.swift#L22 needs bumping?

**Comment by alexwlchan** [comment]
Oops, thanks for flagging. I've just pushed a commit which should fix it.
